/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package logOrSignIn;

import java.awt.Color;

/**
 *
 * @author PC
 */
public class signinPanel extends javax.swing.JFrame {

    /**
     * Creates new form signinPanel
     */
    public signinPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        passwordField = new javax.swing.JPasswordField();
        nameField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        numberField = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NEW USER");
        setBackground(new java.awt.Color(44, 57, 48));
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(400, 450));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setForeground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(220, 215, 201));
        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 70)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("SIGN UP");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(10, 10, 370, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/librarySignin.jpg"))); // NOI18N
        jPanel3.add(jLabel1);
        jLabel1.setBounds(0, -50, 400, 266);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.2;
        getContentPane().add(jPanel3, gridBagConstraints);

        jPanel4.setBackground(new java.awt.Color(63, 79, 68));
        jPanel4.setLayout(null);

        passwordField.setBackground(new java.awt.Color(220, 215, 201));
        passwordField.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        passwordField.setText("PASSWORD");
        passwordField.setActionCommand("<Not Set>");
        passwordField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 4, 1, 1));
        passwordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFieldFocusLost(evt);
            }
        });
        passwordField.setEchoChar((char) 0);
        jPanel4.add(passwordField);
        passwordField.setBounds(190, 210, 170, 30);

        nameField.setBackground(new java.awt.Color(220, 215, 201));
        nameField.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        nameField.setText("FULL NAME");
        nameField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 4, 1, 1));
        nameField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nameField.setMargin(new java.awt.Insets(2, 1, 2, 6));
        nameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameFieldFocusLost(evt);
            }
        });
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });
        jPanel4.add(nameField);
        nameField.setBounds(30, 30, 330, 30);

        emailField.setBackground(new java.awt.Color(220, 215, 201));
        emailField.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        emailField.setText("EMAIL ADDRESS");
        emailField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 4, 1, 1));
        emailField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        emailField.setMargin(new java.awt.Insets(2, 1, 2, 6));
        emailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFieldFocusLost(evt);
            }
        });
        jPanel4.add(emailField);
        emailField.setBounds(30, 150, 330, 30);

        numberField.setBackground(new java.awt.Color(220, 215, 201));
        numberField.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        numberField.setText("CONTACT NUMBER");
        numberField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 4, 1, 1));
        numberField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        numberField.setMargin(new java.awt.Insets(2, 1, 2, 6));
        numberField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                numberFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                numberFieldFocusLost(evt);
            }
        });
        numberField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numberFieldKeyTyped(evt);
            }
        });
        jPanel4.add(numberField);
        numberField.setBounds(30, 210, 140, 30);

        addressField.setBackground(new java.awt.Color(220, 215, 201));
        addressField.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        addressField.setText("ADDRESS");
        addressField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 4, 1, 1));
        addressField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        addressField.setMargin(new java.awt.Insets(2, 1, 2, 6));
        addressField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addressFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addressFieldFocusLost(evt);
            }
        });
        jPanel4.add(addressField);
        addressField.setBounds(30, 90, 330, 30);

        jButton1.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(220, 215, 201));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sign-up-button.png"))); // NOI18N
        jButton1.setText("SIGN UP");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel4.add(jButton1);
        jButton1.setBounds(120, 270, 130, 30);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel4, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusGained
        if (String.valueOf(passwordField.getPassword()).equals("PASSWORD")) {
            passwordField.setText("");
            passwordField.setEchoChar('•');
        }
    }//GEN-LAST:event_passwordFieldFocusGained

    private void passwordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusLost
        if (passwordField.getPassword().length == 0) {
            passwordField.setText("PASSWORD");
            passwordField.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_passwordFieldFocusLost

    private void nameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFieldFocusGained
        if (nameField.getText().equals("FULL NAME")) {
            nameField.setText("");
        }
    }//GEN-LAST:event_nameFieldFocusGained

    private void nameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFieldFocusLost
        if (nameField.getText().isEmpty()) {
            nameField.setText("FULL NAME");
        }
    }//GEN-LAST:event_nameFieldFocusLost

    private void emailFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusGained
        if (emailField.getText().equals("EMAIL ADDRESS")) {
            emailField.setText("");
        }
    }//GEN-LAST:event_emailFieldFocusGained

    private void emailFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusLost
        if (emailField.getText().isEmpty()) {
            emailField.setText("EMAIL ADDRESS");
        }
    }//GEN-LAST:event_emailFieldFocusLost

    private void numberFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numberFieldFocusGained
       if (numberField.getText().equals("CONTACT NUMBER")) {
            numberField.setText("");
        }
    }//GEN-LAST:event_numberFieldFocusGained

    private void numberFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numberFieldFocusLost
        if (numberField.getText().isEmpty()) {
            numberField.setText("CONTACT NUMBER");
        }
    }//GEN-LAST:event_numberFieldFocusLost

    private void addressFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressFieldFocusGained
        if (addressField.getText().equals("ADDRESS")) {
            addressField.setText("");
        }
    }//GEN-LAST:event_addressFieldFocusGained

    private void addressFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressFieldFocusLost
        if (addressField.getText().isEmpty()) {
            addressField.setText("ADDRESS");
        }
    }//GEN-LAST:event_addressFieldFocusLost

    private void numberFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numberFieldKeyTyped
       char c = evt.getKeyChar();
        if (!Character.isDigit(c) || numberField.getText().length() >= 11) { 
            evt.consume(); 
        }
    }//GEN-LAST:event_numberFieldKeyTyped

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signinPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signinPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signinPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signinPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signinPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressField;
    private javax.swing.JTextField emailField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField numberField;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField userIdField;
    private javax.swing.JTextField userIdField1;
    private javax.swing.JTextField userIdField2;
    // End of variables declaration//GEN-END:variables
}
